#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jackrabbit
Version  : 1.5.0
Release  : 3
URL      : https://repo1.maven.org/maven2/org/apache/jackrabbit/jackrabbit-jcr-commons/1.5.0/jackrabbit-jcr-commons-1.5.0.jar
Source0  : https://repo1.maven.org/maven2/org/apache/jackrabbit/jackrabbit-jcr-commons/1.5.0/jackrabbit-jcr-commons-1.5.0.jar
Source1  : https://repo1.maven.org/maven2/org/apache/jackrabbit/jackrabbit-jcr-commons/1.5.0/jackrabbit-jcr-commons-1.5.0.pom
Source2  : https://repo1.maven.org/maven2/org/apache/jackrabbit/jackrabbit-parent/1.5.0/jackrabbit-parent-1.5.0.pom
Source3  : https://repo1.maven.org/maven2/org/apache/jackrabbit/jackrabbit-parent/2.5.2/jackrabbit-parent-2.5.2.pom
Source4  : https://repo1.maven.org/maven2/org/apache/jackrabbit/jackrabbit-webdav/1.5.0/jackrabbit-webdav-1.5.0.jar
Source5  : https://repo1.maven.org/maven2/org/apache/jackrabbit/jackrabbit-webdav/1.5.0/jackrabbit-webdav-1.5.0.pom
Source6  : https://repo1.maven.org/maven2/org/apache/jackrabbit/jackrabbit-webdav/2.5.2/jackrabbit-webdav-2.5.2.jar
Source7  : https://repo1.maven.org/maven2/org/apache/jackrabbit/jackrabbit-webdav/2.5.2/jackrabbit-webdav-2.5.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-jackrabbit-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-jackrabbit package.
Group: Data

%description data
data components for the mvn-jackrabbit package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-jcr-commons/1.5.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-jcr-commons/1.5.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-jcr-commons/1.5.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-jcr-commons/1.5.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-parent/1.5.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-parent/1.5.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-parent/2.5.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-parent/2.5.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-webdav/1.5.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-webdav/1.5.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-webdav/1.5.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-webdav/1.5.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-webdav/2.5.2
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-webdav/2.5.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-webdav/2.5.2
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-webdav/2.5.2


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-jcr-commons/1.5.0/jackrabbit-jcr-commons-1.5.0.jar
/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-jcr-commons/1.5.0/jackrabbit-jcr-commons-1.5.0.pom
/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-parent/1.5.0/jackrabbit-parent-1.5.0.pom
/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-parent/2.5.2/jackrabbit-parent-2.5.2.pom
/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-webdav/1.5.0/jackrabbit-webdav-1.5.0.jar
/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-webdav/1.5.0/jackrabbit-webdav-1.5.0.pom
/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-webdav/2.5.2/jackrabbit-webdav-2.5.2.jar
/usr/share/java/.m2/repository/org/apache/jackrabbit/jackrabbit-webdav/2.5.2/jackrabbit-webdav-2.5.2.pom
